version: "2"
services: 
  app_node:
    container_name: "app_node"
    build:
      context: .
      dockerfile: ./dockerconf/Dockerfile-node
    volumes: 
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - app_mongo:mongo
    expose: 
      - 3002
    ports: 
      - 80:3002
    command: ['npm', 'run', 'test-watch']

  app_mongo:
    container_name: "app_mongo"
    build:
      context: ./dockerconf/.mongo
    ports:
      - 27017:27017