version: "2"
services: 
  app_node:
    container_name: "app_node"
    image: node:6-onbuild
    volumes: 
      - ./:/usr/src/app
    expose: 
      - 3002
    ports: 
      - 80:3002
    command: ['npm', 'run', 'dev']