version: "2"
services: 
  app_node:
    container_name: "app_node"
    build:
      context: .
      dockerfile: ./dockerconf/Dockerfile-node
    volumes: 
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    expose: 
      - 3002
    ports: 
      - 80:3002
    command: ['npm', 'run', 'dev']